version: '2'

services:

  bdd_h2:
    build:
      context: ..
      dockerfile: dockers/db/Dockerfile_h2
    image: vmickaelv/bdd_computer_database:h2

    networks:
      - back

    ports:
      - "8081:81"
      - "1521:1521"

  # Lance la BDD
  bdd_mysql:
    build:
      context: ..
      dockerfile: dockers/db/Dockerfile_mysql
    image: vmickaelv/bdd_computer_database:mysql
    networks:
      - back
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"

  bdd:
    extends: bdd_h2

  # Serveurs de tests
  server_tomcat:
    build:
      context: ..
      dockerfile: dockers/Dockerfile_tomcat_server

    networks:
      - back
      - front

    ports:
      - "8888:8080"

    environment:
      - CATALINA_OPTS=$CATALINA_OPTS -Ddb.min_size=25 -Ddb.username=sa -Ddb.password= -Ddb.className=org.h2.Driver -Ddb.url=jdbc:h2:tcp://bdd:1521/~/test

  server:
    extends: server_tomcat

    depends_on:
      - bdd

networks:
  front:

  back: