version: '2'

services:

  # Lance la BDD
  bdd:
    build:
      context: ..
      dockerfile: dockers/db/Dockerfile_mysql
    networks:
      - back
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    # TODO a supprimer
    ports :
      - "3306:3306"

  # Service mère pour les tests
  base_test:
    build:
      context: ..
      dockerfile: dockers/Dockerfile_java_maven
    volumes:
          - ~/.m2/repository:/root/.m2/repository

  # Lancement des tests unitaires
  unit_test:
    extends: base_test
    networks:
      - back
      - front
    depends_on:
      - bdd
#      - firefox
    command:
      - "mvn"
      - "test"

  # Lancement des tests fonctionnels
  selenium_test:
    extends: base_test
    networks:
      - front
    depends_on:
      - test_server
      - firefox
    command:
      - "mvn"
      - "test"
      - "-P"
      - "seleniumTest"
      - "-Dserver.ip=test_server"
      - "-Dserver.port=8888"
      - "-Dwebdriver.url=http://firefox:4444/wd/hub"

        # TODO Voir si sleep important ou pas
#       - "sh"
#       - "-c"
#       - "sleep 3 && mvn test -P seleniumTest -Dserver.ip=server -Dwebdriver.url=http://firefox:4444/wd/hub"

  # Lance le firefox Distant pour les tests fonctionnelles
  firefox:
    image: selenium/standalone-firefox-debug:2.52.0
    ports:
      - "4444:4444"
      - "5900:5900"
    networks:
      - front

  # Serveur de tests
  test_server:
    extends: base_test

    networks:
      - back
      - front

#    expose:
#      - "8888"

    ports:
      - "8888:8888"

    depends_on:
      - bdd


    command:
      - "mvn"
      - "-P"
      - "docker"
      - "tomcat7:run"

  # Serveur de Production ?
  tomcat_webapp:
    build:
      context: ..
      dockerfile: dockers/Dockerfile_tomcat_server

    ports:
      - "8888:8080"

    depends_on:
      - bdd

    networks:
      - back
      - front

networks:
  front:

  back: